
version: '2'

services:
  vscode-spotify-lyrics:
    image: vscode-spotify-lyrics:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 app.js
